### PR TITLE
Create Swedish translation

### PR DESCRIPTION
**Pull request by eson57**
Complete Swedish translation if wanted.
Thanks for this app. A must have for Alien Dalvik on Sailfish OS

### CODE REVIEW

**Comment by Umeaboy** [comment]
I have already opened a request for Swedish. Why open a new one?

**Comment by eson57** [comment]
Because this one is correct and complete.

**Comment by Umeaboy** [comment]
Okey, but you could've just corrected mine instead of making a duplicate. :)

**Comment by eson57** [comment]
I didn't actually notice yours before I made mine. Sorry for that.

**Comment by eson57** [comment]
No interest at all?

**Comment by Umeaboy** [comment]
Apparently Sergey has abandoned the project for some reason, or at least the translation part of it.

**Comment by eson57** [comment]
Let's not take anything in advance, but I wouldn't be surprised. To annoy big american companies usually comes with a price.

**Pull request closed without merging**
