### PR TITLE
Make ota zip compatible with addond-v2 and system-as-root devices

### PR DESCRIPTION
**Pull request by Yannik**

### CODE REVIEW

**Comment by Yannik** [comment]
Is there any additional information that is required? I have tested this and can confirm it works.

**Comment by ale5000-git** [comment]
@Yannik

Hi,
my message isn't related to Yalp Store but I don't know how to contact you privately.
My [OTA zip](https://github.com/micro5k/microg-unofficial-installer) should be already compatible with system-as-root devices but I cannot test it.
If possible it would be nice if you can test it and report back.

**Comment by Yannik** [comment]
Hey @ale5000-git,

this is the addon.d script I'm using in my own microg.zip:
```#!/sbin/sh
#
# ADDOND_VERSION=2
#

. /tmp/backuptool.functions

PACKAGE_NAME=GmsCore

list_files() {
cat <<EOF
priv-app/${PACKAGE_NAME}.apk
priv-app/${PACKAGE_NAME}/${PACKAGE_NAME}.apk
EOF
}

case "$1" in
  backup)
    list_files | while read FILE DUMMY; do
      backup_file $S/"$FILE"
    done
  ;;
  restore)
    list_files | while read FILE REPLACEMENT; do
      R=""
      [ -n "$REPLACEMENT" ] && R="$S/$REPLACEMENT"
      [ -f "$C/$S/$FILE" ] && restore_file $S/"$FILE" "$R"
    done
  ;;
  pre-backup)
    # Stub
  ;;
  post-backup)
    # Stub
  ;;
  pre-restore)
    # Stub
  ;;
  post-restore)
    # Stub
  ;;
esac
```

Yours does look a bit complicated to me ;-)
Hope this helps!

**Comment by ale5000-git** [comment]
@Yannik

My addon.d script is already working, I'm worrying only for the main installation of the zip under these devices

**Comment by Yannik** [comment]
@yeriomin, your `update-binary` is unfortunately not working on all devices. F-Droid had the same issue which is documented here: https://gitlab.com/fdroid/privileged-extension/merge_requests/34

Hence this PR.

**Comment by ale5000-git** [comment]
@Yannik
My issue isn't for Yalp Store but for [this](https://github.com/micro5k/microg-unofficial-installer), I'm writing here to you just because it is difficult to find people with these devices that can help.

**Comment by Yannik** [comment]
@ale5000-git Can you please just open an issue on your repo and reference me there.

**Comment by ale5000-git** [comment]
[Done](https://github.com/micro5k/microg-unofficial-installer/issues/17).

**Comment by curbengh** [comment]
Closes https://github.com/yeriomin/YalpStore/issues/512

**Pull request closed without merging**
